[project]
name = "elec-research"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "defusedxml>=0.7.1",
    "jinja2>=3.1.6",
    "lxml>=6.0.2",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "pandas>=3.0.1",
    "pillow>=12.1.1",
    "scikit-image>=0.26.0",
    "scipy>=1.17.1",
    "tqdm>=4.67.3",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
